fix: do not reload entities after saving #182829
audaciaconsulting/Audacia.Seed pull request #5
Opened 2024-10-30 16:18 UTC by OwenLacey28

| Action | Done? |
| --- | --- |
| CHANGELOG updated | ✔/❌ |
| Code compiles and unit tests all pass locally | ✔/❌ |
| Debug/console log code removed | ✔/❌ |
| Commented out code removed | ✔/❌ |
| Unit tests added/updated | ✔/❌ |
| README updated | ✔/❌ |
| Considered: <br /> - Performance <br /> - Security <br /> - Logging | ✔/❌ |
| Licenses of any new/upgraded dependencies checked, with no copyleft dependencies introduced | ✔/❌ |

2024-10-30 16:19 UTC, OwenLacey28 commented on src/Audacia.Seed.EntityFrameworkCore/Repositories/EntityFrameworkCoreSeedableRepository.cs
> -        _afterSaveJobs.Add(() => _context.Entry(entity).Reload());
this is the 'change'. The rest of it is making the tests work

2024-10-30 16:19 UTC, OwenLacey28 commented on src/Audacia.Seed/Customisation/EntitySeedExtensions.cs
> +        if (getter.Body is MemberExpression m && m.Expression?.Type != typeof(TEntity))
made these work like the existing WithDifferent method for nesting properties

2024-11-05 14:29 UTC, Audacia-RhysSmith commented on docs/adr/0001-clear-the-ef-core-change-tracker.md
> +# 1. Clear the EF Core change tracker
Thanks for adding this, helps explain the changes

2024-11-05 14:29 UTC, Audacia-RhysSmith approved these changes

2024-11-05 14:44 UTC, Audacia-RhysSmith requested changes
![image](https://github.com/user-attachments/assets/cdbdb6ea-bc33-43a2-bd9a-8b5f39f66d58)
Just ran the tests and got this, is this something from the change?

2024-11-05 15:50 UTC, OwenLacey28 commented
> ![image](https://private-user-images.githubusercontent.com/79139905/383192333-cdbdb6ea-bc33-43a2-bd9a-8b5f39f66d58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjAyMDMsIm5iZiI6MTczMDgxOTkwMywicGF0aCI6Ii83OTEzOTkwNS8zODMxOTIzMzMtY2RiZGI2ZWEtYmMzMy00M2EyLWJkOWEtOGI1ZjM5ZjY2ZDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE1MTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMDgwZTE5NjQwNjliMThkMzJkY2ZhZmEzYzBmZGI2YjljNmYwMTBmNDE4YjE0MzA4MTRlN2FkYWY4YTQ1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GPVFoxEGYXwsehnHuJ793JI3i2CIJJ-Db-Zqlycfp9U) Just ran the tests and got this, is this something from the change?

this is what happens when you run against a real SQL db - so it's expected for you to see this at the start of your first test run

2024-11-05 16:49 UTC, Audacia-RhysSmith approved these changes

2024-11-05 16:49 UTC, merged